# Generated by Django 5.0.4 on 2024-04-15 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToolModuleGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ToolSensorType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("sensor_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ToolModuleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("module_type_id", models.TextField(blank=True, null=True)),
                ("hash_code", models.TextField(blank=True, null=True)),
                (
                    "r_modules_group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.toolmodulegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ToolModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sn", models.TextField(blank=True, max_length=255, null=True)),
                ("dbdate", models.DateField(blank=True, null=True)),
                ("dbversion", models.DateField(blank=True, null=True)),
                ("dbsn", models.TextField(blank=True, null=True)),
                ("dbcomment", models.TextField(blank=True, null=True)),
                ("dbtname", models.TextField(blank=True, null=True)),
                ("dbtlength", models.FloatField(blank=True, null=True)),
                ("dbtweight", models.FloatField(blank=True, null=True)),
                ("dbtmax_od", models.FloatField(blank=True, null=True)),
                ("dbtmax_od_collapsed", models.FloatField(blank=True, null=True)),
                ("dbtmax_od_opened", models.FloatField(blank=True, null=True)),
                ("dbtimage2d", models.FloatField(blank=True, null=True)),
                ("dbtimage_h_shift", models.FloatField(blank=True, null=True)),
                ("dbtimage_h_scale", models.FloatField(blank=True, null=True)),
                ("dbtimage_h_y1", models.FloatField(blank=True, null=True)),
                ("dbtimage_h_y2", models.FloatField(blank=True, null=True)),
                ("dbtcomp_str", models.FloatField(blank=True, null=True)),
                ("image", models.BinaryField(blank=True, null=True)),
                (
                    "r_module_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.toolmoduletype",
                    ),
                ),
            ],
            options={
                "ordering": ("sn",),
            },
        ),
        migrations.CreateModel(
            name="ToolInstalledSensor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_point", models.FloatField(blank=True, null=True)),
                (
                    "r_toolmodule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.toolmodule"
                    ),
                ),
                (
                    "r_toolsensortype_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.toolsensortype",
                    ),
                ),
            ],
        ),
    ]
