# Generated by Django 5.0.4 on 2024-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolmodule",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
