# Generated by Django 5.0.4 on 2024-04-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_toolmodule_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtimage2d",
        ),
    ]
