# Generated by Django 5.0.4 on 2024-04-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_toolmodule_dbtimage2d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolmodule",
            name="dbversion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
