# Generated by Django 5.0.4 on 2024-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_toolmodule_dbversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolmodule",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
