# Generated by Django 5.0.6 on 2024-06-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_toolmodule_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtcomp_str",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtimage_h_scale",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtimage_h_shift",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtimage_h_y1",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtimage_h_y2",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtlength",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtmax_od",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtmax_od_collapsed",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtmax_od_opened",
        ),
        migrations.RemoveField(
            model_name="toolmodule",
            name="dbtweight",
        ),
    ]
