# Generated by Django 5.0.6 on 2024-06-03 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_toolmodule_dbtcomp_str_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceString",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("en", models.TextField()),
                ("ru", models.TextField()),
                ("es", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_unisum", models.IntegerField(blank=True, null=True)),
                (
                    "name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.resourcestring",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_unisum", models.IntegerField(blank=True, null=True)),
                (
                    "html_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.resourcestring",
                    ),
                ),
                (
                    "name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name",
                        to="api.resourcestring",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasureUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measure_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.measure"
                    ),
                ),
                (
                    "unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.unit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="default_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.unit"
            ),
        ),
        migrations.CreateModel(
            name="UnitSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.resourcestring",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitSystemMeasureUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measure_unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.measureunit",
                    ),
                ),
                (
                    "unit_system_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.unitsystem"
                    ),
                ),
            ],
        ),
    ]
