# Generated by Django 5.0.6 on 2024-06-03 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_resourcestring_measure_unit_measureunit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameter_name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConversionFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("factor_1", models.FloatField(blank=True, null=True)),
                ("factor_2", models.FloatField(blank=True, null=True)),
                (
                    "from_unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_units",
                        to="api.unit",
                    ),
                ),
                (
                    "to_unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_units",
                        to="api.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameter_value", models.FloatField(blank=True, null=True)),
                (
                    "toolmodule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.toolmodule"
                    ),
                ),
                (
                    "unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.unit"
                    ),
                ),
                (
                    "parameter_type_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.parametertype",
                    ),
                ),
            ],
        ),
    ]
