# Generated by Django 5.0.6 on 2024-06-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversionfactor",
            old_name="from_unit_id",
            new_name="from_unit",
        ),
        migrations.RenameField(
            model_name="conversionfactor",
            old_name="to_unit_id",
            new_name="to_unit",
        ),
        migrations.RenameField(
            model_name="measure",
            old_name="name_id",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="measureunit",
            old_name="measure_id",
            new_name="measure",
        ),
        migrations.RenameField(
            model_name="measureunit",
            old_name="unit_id",
            new_name="unit",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="parameter_type_id",
            new_name="parameter_type",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="toolmodule_id",
            new_name="toolmodule",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="unit_id",
            new_name="unit",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="unitsystem_id",
            new_name="unitsystem",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="toolinstalledsensor",
            old_name="r_toolmodule_id",
            new_name="r_toolmodule",
        ),
        migrations.RenameField(
            model_name="toolinstalledsensor",
            old_name="r_toolsensortype_id",
            new_name="r_toolsensortype",
        ),
        migrations.RenameField(
            model_name="toolmodule",
            old_name="r_module_type_id",
            new_name="r_module_type",
        ),
        migrations.RenameField(
            model_name="toolmoduletype",
            old_name="module_type_id",
            new_name="module_type",
        ),
        migrations.RenameField(
            model_name="toolmoduletype",
            old_name="r_modules_group_id",
            new_name="r_modules_group",
        ),
        migrations.RenameField(
            model_name="toolsensortype",
            old_name="sensor_id",
            new_name="sensor",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="name_id",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="unitsystem",
            old_name="name_id",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="unitsystemmeasureunit",
            old_name="measure_unit_id",
            new_name="measure_unit",
        ),
        migrations.RenameField(
            model_name="unitsystemmeasureunit",
            old_name="unit_system_id",
            new_name="unit_system",
        ),
    ]
