# Generated by Django 5.0.6 on 2024-06-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_from_unit_id_conversionfactor_from_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="default_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unit",
            ),
        ),
        migrations.AlterField(
            model_name="measureunit",
            name="measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.measure",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="parameter_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.parametertype"
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unit",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="unitsystem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unitsystem",
            ),
        ),
        migrations.AlterField(
            model_name="resourcestring",
            name="en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcestring",
            name="es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcestring",
            name="ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="html_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.resourcestring",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name",
                to="api.resourcestring",
            ),
        ),
    ]
