# Generated by Django 5.0.6 on 2024-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_measure_default_unit_alter_measureunit_measure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
