# Generated by Django 5.0.6 on 2024-06-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametertype",
            name="default_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.measure",
            ),
        ),
        migrations.AddField(
            model_name="toolinstalledsensor",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unit",
            ),
        ),
        migrations.AddField(
            model_name="toolmodule",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
